# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: restaurant.proto for package 'restaurant'

require 'grpc'
require 'restaurant_pb'

module Restaurant
  module Cookbook
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'restaurant.Cookbook'

      rpc :GetRecipe, RecipeRequest, RecipeResponse
    end

    Stub = Service.rpc_stub_class
  end
end
