# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "restaurant.RecipeRequest" do
    optional :name, :string, 1
  end
  add_message "restaurant.RecipeResponse" do
    optional :recipe, :message, 1, "restaurant.Recipe"
  end
  add_message "restaurant.Recipe" do
    repeated :ingredients, :string, 1
  end
end

module Restaurant
  RecipeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("restaurant.RecipeRequest").msgclass
  RecipeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("restaurant.RecipeResponse").msgclass
  Recipe = Google::Protobuf::DescriptorPool.generated_pool.lookup("restaurant.Recipe").msgclass
end
